name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.x'
  NUGET_PACKAGE_NAME: 'Anonymiser'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Generate Version Number
      id: version
      run: |
        DATE=$(date +%Y%m%d)
        RUN_NUMBER=$(printf "%03d" $GITHUB_RUN_NUMBER)
        echo "VersionNumber=1.0.$DATE.$RUN_NUMBER" >> $GITHUB_ENV

    - name: Restore dependencies
      run: |
        dotnet restore src/Anonymiser/Anonymiser.csproj
        dotnet restore test/Anonymiser.Tests/Anonymiser.Tests.csproj

    - name: Build
      run: |
        dotnet build src/Anonymiser/Anonymiser.csproj --configuration Release -p:VersionNumber=${{ env.VersionNumber }}
        dotnet build test/Anonymiser.Tests/Anonymiser.Tests.csproj --configuration Release

    - name: Test
      run: dotnet test test/Anonymiser.Tests/Anonymiser.Tests.csproj --no-build --configuration Release

    - name: Pack
      run: dotnet pack src/Anonymiser/Anonymiser.csproj --configuration Release --no-build --output ./artifacts -p:VersionNumber=${{ env.VersionNumber }}

    - name: Upload NuGet package
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: ./artifacts/*.nupkg

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Download NuGet package
      uses: actions/download-artifact@v4
      with:
        name: nuget-package
        path: ./artifacts

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }} 